apiVersion: gitlab.jcrose.top/v1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: jcrose-cmdb-operator
    app.kubernetes.io/managed-by: kustomize
  name: app-sample
spec:
  # TODO(user): Add fields here
